<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameServer.Abstractions\GameServer.Abstractions.csproj" />
    <ProjectReference Include="..\GameServer.Contracts\GameServer.Contracts.csproj" />
  </ItemGroup>

</Project>
