using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GameServer.Infrastructure.Persistence.Migrations;

/// <summary>创建业务表并接管已知 MVP 旧表结构，保留已有账号、流水及 Orleans 系统表。</summary>
public partial class InitialGameSchema : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        // 此基线只使用创建缺失对象的 SQL；后续结构演进由常规 EF 迁移完成。
        migrationBuilder.Sql("""
            DROP INDEX IF EXISTS "IX_LedgerEntries_OperationId";
            CREATE TABLE IF NOT EXISTS "AspNetRoles" (
                "Id" text NOT NULL,
                "Name" character varying(256),
                "NormalizedName" character varying(256),
                "ConcurrencyStamp" text,
                CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
            );

            CREATE TABLE IF NOT EXISTS "AspNetUsers" (
                "Id" text NOT NULL,
                "UserName" character varying(256),
                "NormalizedUserName" character varying(256),
                "Email" character varying(256),
                "NormalizedEmail" character varying(256),
                "EmailConfirmed" boolean NOT NULL,
                "PasswordHash" text,
                "SecurityStamp" text,
                "ConcurrencyStamp" text,
                "PhoneNumber" text,
                "PhoneNumberConfirmed" boolean NOT NULL,
                "TwoFactorEnabled" boolean NOT NULL,
                "LockoutEnd" timestamp with time zone,
                "LockoutEnabled" boolean NOT NULL,
                "AccessFailedCount" integer NOT NULL,
                CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
            );

            CREATE TABLE IF NOT EXISTS "ContentReleases" (
                "Version" text NOT NULL,
                "ContentJson" text NOT NULL,
                "ImportedBy" text NOT NULL,
                "ImportedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_ContentReleases" PRIMARY KEY ("Version")
            );

            CREATE TABLE IF NOT EXISTS "ContentSettings" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "ActiveVersion" text NOT NULL,
                CONSTRAINT "PK_ContentSettings" PRIMARY KEY ("Id")
            );

            CREATE TABLE IF NOT EXISTS "LedgerEntries" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
                "OperationId" text NOT NULL,
                "CharacterId" text NOT NULL,
                "Kind" character varying(64) NOT NULL,
                "ItemId" text NOT NULL,
                "Quantity" integer NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_LedgerEntries" PRIMARY KEY ("Id")
            );

            CREATE TABLE IF NOT EXISTS "PlayerItemProjections" (
                "CharacterId" text NOT NULL,
                "ItemId" text NOT NULL,
                "Quantity" integer NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_PlayerItemProjections" PRIMARY KEY ("CharacterId", "ItemId")
            );

            CREATE TABLE IF NOT EXISTS "RewardOperations" (
                "OperationId" text NOT NULL,
                "CharacterId" text NOT NULL,
                "Kind" text NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_RewardOperations" PRIMARY KEY ("OperationId")
            );

            CREATE TABLE IF NOT EXISTS "AspNetRoleClaims" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "RoleId" text NOT NULL,
                "ClaimType" text,
                "ClaimValue" text,
                CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS "AspNetUserClaims" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "UserId" text NOT NULL,
                "ClaimType" text,
                "ClaimValue" text,
                CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS "AspNetUserLogins" (
                "LoginProvider" text NOT NULL,
                "ProviderKey" text NOT NULL,
                "ProviderDisplayName" text,
                "UserId" text NOT NULL,
                CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
                CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS "AspNetUserRoles" (
                "UserId" text NOT NULL,
                "RoleId" text NOT NULL,
                CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
                CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
                CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS "AspNetUserTokens" (
                "UserId" text NOT NULL,
                "LoginProvider" text NOT NULL,
                "Name" text NOT NULL,
                "Value" text,
                CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
                CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
            );

            CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

            CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

            CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

            CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

            CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

            CREATE INDEX IF NOT EXISTS "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

            CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_LedgerEntries_OperationId_ItemId" ON "LedgerEntries" ("OperationId", "ItemId");
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
        => throw new NotSupportedException("The baseline may adopt existing player data and cannot be rolled back automatically.");
}